import { useMemo, useState } from 'react'
import { BookOpen, Brain, CheckCircle2, Clipboard, Download, Search, Sparkles } from 'lucide-react'
import SummaryMarkdown from './SummaryMarkdown'
import { extractTerms, extractTimeline, getReadingStats } from '../lib/learning'
import { BookmarkButton, NotebookPanel, TimelinePanel, TutorPanel } from './LearningPanels'

export default function SummaryWorkspace({ summary, fileName, pageCount, summaryId, learning: savedLearning, onLearningChange }) {
  const [tab, setTab] = useState('summary'); const [query, setQuery] = useState(''); const [card, setCard] = useState(0); const [revealed, setRevealed] = useState(false); const [copied, setCopied] = useState(false); const [learning, setLearning] = useState(savedLearning || {})
  const terms = useMemo(() => extractTerms(summary), [summary]); const timeline = useMemo(() => extractTimeline(summary), [summary]); const stats = useMemo(() => getReadingStats(summary), [summary]); const canSave = Boolean(summaryId && onLearningChange)
  const filtered = query ? summary.split('\n').filter((line) => line.toLowerCase().includes(query.toLowerCase())).join('\n') : summary
  const download = (extension) => { const plain = extension === 'txt' ? summary.replace(/[#*_`]/g, '') : summary; const url = URL.createObjectURL(new Blob([plain], { type: 'text/plain' })); const anchor = document.createElement('a'); anchor.href = url; anchor.download = `${fileName?.replace(/\.pdf$/i, '') || 'briefwise-summary'}.${extension}`; anchor.click(); URL.revokeObjectURL(url) }
  const copy = async () => { await navigator.clipboard.writeText(summary); setCopied(true); setTimeout(() => setCopied(false), 1800) }
  const moveCard = (direction) => { setCard(card + direction); setRevealed(false) }
  const persistLearning = async (next) => { setLearning(next); if (canSave) await onLearningChange(next) }
  const tabs = [['summary', BookOpen, 'Brief'], ['study', Brain, 'Study'], ['quiz', CheckCircle2, 'Recall'], ['timeline', Sparkles, 'Timeline'], ['notes', Clipboard, 'Notebook'], ['tutor', Search, 'Tutor']]
  return <section className="summary-workspace">
    <header className="workspace-header"><div><span className="eyebrow"><Sparkles size={14}/> Learning desk</span><h2>{fileName || 'Your document brief'}</h2><p>{pageCount ? `${pageCount} pages / ` : ''}{stats.words} words / ~{stats.minutes} min read</p></div><div className="action-row"><BookmarkButton bookmarked={Boolean(learning.bookmarked)} disabled={!canSave} onToggle={() => persistLearning({ ...learning, bookmarked: !learning.bookmarked })}/><button onClick={copy} className="icon-button"><Clipboard size={17}/>{copied ? 'Copied' : 'Copy'}</button><button onClick={() => download('md')} className="icon-button"><Download size={17}/> .md</button><button onClick={() => download('txt')} className="icon-button">.txt</button></div></header>
    <div className="workspace-tabs">{tabs.map(([id, Icon, label]) => <button key={id} onClick={() => setTab(id)} className={tab === id ? 'active' : ''}><Icon size={16}/>{label}</button>)}</div>
    {tab === 'summary' && <><label className="smart-search"><Search size={17}/><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search within this brief" aria-label="Search summary"/>{query && <button onClick={() => setQuery('')}>Clear</button>}</label>{query && !filtered && <p className="empty-state">No matching text in this brief.</p>}<SummaryMarkdown>{filtered}</SummaryMarkdown>{terms.length > 0 && <aside className="glossary"><h3>Glossary</h3><div>{terms.map(({ term, definition }) => <span className="term-chip" key={term} tabIndex="0">{term}<span role="tooltip">{definition}</span></span>)}</div><p>Hover or focus a term to see its definition.</p></aside>}</>}
    {tab === 'study' && <div className="study-panel">{terms.length ? <><p className="study-count">Card {card + 1} of {terms.length}</p><button className="flashcard" onClick={() => setRevealed(!revealed)}><span>{revealed ? terms[card].definition : terms[card].term}</span><small>{revealed ? 'Definition - click to hide' : 'Click to reveal definition'}</small></button><div className="study-controls"><button disabled={card === 0} onClick={() => moveCard(-1)}>Previous</button><button disabled={card === terms.length - 1} onClick={() => moveCard(1)}>Next</button></div></> : <p className="empty-state">No detected key terms are available for flashcards.</p>}</div>}
    {tab === 'quiz' && <div className="study-panel"><h3>Self-check prompts</h3><ol className="quiz-list"><li>What is the central idea of this document?</li><li>Which takeaway would matter most to your work or study?</li>{terms.slice(0, 3).map(({ term }) => <li key={term}>How would you explain <strong>{term}</strong> in your own words?</li>)}</ol><p className="muted">Use the brief and glossary to check your answers.</p></div>}
    {tab === 'timeline' && <TimelinePanel events={timeline}/>} {tab === 'notes' && <NotebookPanel learning={learning} onSave={persistLearning} canSave={canSave}/>} {tab === 'tutor' && <TutorPanel summary={summary}/>} 
  </section>
}
